config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :comments
    root 'session#welcome_page'
    get 'session/login'
    get 'session/welcome_page'
    post 'session/create'
    get 'session/logout'
    resources :users
    resources :posts
    resources :games
  end
end

app/controllers/session_controller.rb
# frozen_string_literal: true

# class for controlling session
class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create welcome_page]
  def login; end

  def welcome_page; end

  def create
    user = User.find_by_nickname params[:user]

    if user&.authenticate params[:password]
      sign_in user
      user.update_last_login
      redirect_to games_path
    else
      redirect_to session_login_path
      flash[:warning] = 'Wrong login or password!'
    end
  end

  def logout
    sign_out
    redirect_to session_welcome_page_path
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 20.days }
    user.update_last_login
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id cookies.signed[:user_id]
  end
end

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/login.html.erb
<%= stylesheet_link_tag "users_common", media: "all", "data-turbolinks-track": "reload" %>

<main>

  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" role="alert" style="width: fit-content">
      <%= value %>
    </div>
    <br>
  <% end %>

  <h1><%= t '.auth' %></h1>

  <h3><%= t '.msg' %></h3>

  <%= form_with url: session_create_url do |form| %>
    <div class="mb-3" style="width: 200px;">
      <%= form.label :user, "#{t '.nickname'}" %> <br>
      <%= form.text_field :user, placeholder: 'user', class: 'form-control', required: true %>
    </div>
    <div class="mb-3" style="width: 200px;">
      <%= form.label :password, "#{t '.password'}" %> <br>
      <%= form.password_field :password, placeholder: '1234', class: 'form-control', required: true %> <br>
    </div>
    <%= form.submit "#{t '.log_in'}", class:'btn btn-primary'%>
  <% end %>

  <br>

  <% if !signed_in? %>
    <%= link_to "#{t '.sign_in'}", new_user_path, class: 'btn btn-success' %>
    <br>
  <% else %>
    <%= link_to "#{t '.log_out'}", session_logout_path, class:'btn btn-warning' %> <br>
  <% end %>

  <br>

  <h5><%= link_to "#{t '.users'}", users_path, class:'btn btn-info' %></h5>

</main>

app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>

app/views/session/welcome_page.html.erb
<%= stylesheet_link_tag "welcome_page", media: "all", "data-turbolinks-track": "reload" %>

<header style="text-align: center; margin-top: 250px" class="welcome">
  <h1>TeamFinder</h1>
  <h3> <%= t '.desc' %> </h3> <br>
  <% if !signed_in? %>
    <%= link_to (t '.enter'), session_login_path, class:"btn btn-primary btn-lg" %> <br> <br>
    <%= link_to (t '.log_in'), new_user_path, class: 'btn btn-success btn-lg' %>
  <% else %>
    <%= link_to "#{t '.go'}", games_path, class:'btn btn-success btn-lg' %>
  <% end %>
</header>