config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :comments
    root 'session#welcome_page'
    get 'session/login'
    get 'session/welcome_page'
    post 'session/create'
    get 'session/logout'
    resources :users
    resources :posts
    resources :games
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_one_attached :image

  has_many :posts, dependent: :destroy

  validates_presence_of :name, :creator

  validates_uniqueness_of :name
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: %i[show edit update destroy]
  skip_before_action :require_login, only: :index

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show; end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit; end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)
    @game.creator = @current_user.nickname

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), success: 'Игра была успешно добавлена.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), success: 'Игра была успешно обновлена.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, success: 'Игра была успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:name, :creator, :image)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3" style="width: 350px;">
    <%= form.label :name, "#{ t '.name' }", style: "display: block" %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="mb-3" style="width: 350px;">
    <%= form.label :image, "#{ t '.pic' }", style: "display: block;" %>
    <% if game.image.attached? %>
      <%= image_tag game.image, style: 'width: 200px; display: block;' %> <br>
    <% end %>
    <%= form.file_field :image, class: 'form-control', accept: 'image/jpg, image/png, image/jpeg' %>
    <div class="form-text" style="width: 300px"><%= t '.comm' %></div>
  </div>

  <div>
    <% if action_name == 'new' %>
      <%= form.submit "#{ t '.add' }", class:'btn btn-success' %>
    <% else %>
      <%= form.submit "#{ t '.edit' }", class:'btn btn-success' %>
    <% end %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong style="color: white"><%= t '.created_by' %>:</strong>
    <span style="color:white;"><%= game.creator %></span>
  </p>
  <p>
    <strong style="color: white"><%= t '.name' %>:</strong>
    <span style="color: white"><%= game.name %> </span>
  </p>

  <p>
    <strong style="color: white"><%= t '.pic' %>:</strong> <br>
    <% if game.image.attached? %>
      <%= image_tag game.image, style: 'width: 500px;'%>
    <% else %>
      <%= image_tag 'default.jpg', style: 'width: 500px;' %>
    <% end %>
  </p>

</div>

app/views/games/edit.html.erb
<%= stylesheet_link_tag "games_common", media: "all", "data-turbolinks-track": "reload" %>
<%= stylesheet_link_tag "games_edit_new_show", media: "all", "data-turbolinks-track": "reload" %>

<main>
  <div class="game-wrapper">
      <div class="game">
          <h1><%= t '.edit_t' %></h1>
          <% if @current_user.nickname == @game.creator || @current_user.is_admin %>
            <%= render "form", game: @game %>
          <% else %>
            <div class="alert alert-danger">
              <%= t '.warning' %>
            </div>
          <% end %>
      </div>
  </div>

  <br>

  <div style="text-align: center">
    <%= link_to "#{ t '.show' }", @game, class: 'btn btn-warning' %> |
    <%= link_to "#{ t '.games' }", games_path, class: 'btn btn-warning' %>
  </div>

</main>

app/views/games/index.html.erb
<%= stylesheet_link_tag "games_common", media: "all", "data-turbolinks-track": "reload" %>
<%= stylesheet_link_tag "games_index", media: "all", "data-turbolinks-track": "reload" %>

<main>

  <div style="width: fit-content; margin: auto;">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" role="alert" style="width: fit-content">
      <%= value %>
    </div>
    <br>
  <% end %>
  </div>

  <h2 style="text-align: center"><%= t '.game_list' %></h2>

  <div id="games" class="d-flex flex-column bd-highlight mb-3">
    <% @games.each do |game| %>
      <div class="full-wrapper">
      <div class="main-part">
        <%= link_to posts_path + "?game=#{game.name}" do %>
          <% if game.image.attached? %>
              <%= image_tag game.image, class: 'game' %>
          <% else %>
            <%= image_tag 'default.jpg', class: 'game' %>
          <% end %>
        <% end %>
        <div class="desc-part">
          <div class="desc-text">
            <%= game.name %>
          </div>
        </div>
      </div>
      <div class="link-part">
        <div class="link-text">
          <h3><%= link_to "#{ t '.game_info' }", game, class: 'btn btn-warning' %></h3>
        </div>
      </div>
      </div>
    <% end %>
  </div>

  <% if signed_in? %>
    <h4 style="text-align: center"><%= link_to "#{ t '.add' }", new_game_path, class: 'btn btn-info' %></h4>
  <% end %>
</main>

app/views/games/new.html.erb
<%= stylesheet_link_tag "games_common", media: "all", "data-turbolinks-track": "reload" %>
<%= stylesheet_link_tag "games_edit_new_show", media: "all", "data-turbolinks-track": "reload" %>

<main>

  <div class="game-wrapper">
  <div class="game">
  <h1><%= t '.add' %></h1>

    <%= render "form", game: @game %> <br>
    <%= link_to "#{ t '.games' }", games_path, class: 'btn btn-info' %>
  </div>
  </div>

  <br>

</main>

app/views/games/show.html.erb
<%= stylesheet_link_tag "games_common", media: "all", "data-turbolinks-track": "reload" %>
<%= stylesheet_link_tag "games_edit_new_show", media: "all", "data-turbolinks-track": "reload" %>

<main style="text-align: center">

<p style="color: green"><%= notice %></p>

  <div class="game-wrapper">
  <div class="game">
<%= render @game %>
  </div>
  </div>

  <br>

  <% if @current_user.nickname == @game.creator || @current_user.is_admin %>
    <%= link_to "#{ t '.edit' }", edit_game_path(@game), class: 'btn btn-warning' %> |
  <% end %>
  <%= link_to "#{ t '.games' }", games_path, class: 'btn btn-warning'%>

  <br> <br>

  <% if @game.creator == @current_user.nickname || @current_user.is_admin %>
    <%= button_to "#{ t '.delete' }", @game, method: :delete, class: 'btn btn-danger' %>
  <% end %>

</main>