config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :comments
    root 'session#welcome_page'
    get 'session/login'
    get 'session/welcome_page'
    post 'session/create'
    get 'session/logout'
    resources :users
    resources :posts
    resources :games
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title

  belongs_to :game
  belongs_to :user

  has_many :comments, dependent: :destroy

  has_rich_text :body
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :check_game, except: :index
  skip_before_action :require_login, only: :index

  # GET /posts or /posts.json
  def index
    _set_game params[:game]
    @posts = current_game.posts.all
    @current_user ||= User.find_by_id cookies.signed[:user_id]
  end

  # GET /posts/1 or /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = current_game.posts.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts or /posts.json
  def create
    @post = current_game.posts.new(post_params)
    @post.user_id = @current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), success: 'Пост успешно сохранен.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), success: 'Пост успешно обновлен.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, success: 'Пост успешно удален.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def check_game
    return if game_set?

    flash[:warning] = 'Сначала выберите игру'
    redirect_to games_path
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def _set_game(game)
    return unless params[:game]

    cookies[:current_game] = { value: game }
  end

  def clean_game_cookies
    cookies[:current_game] = nil
  end

  def game_set?
    !cookies[:current_game].nil?
  end

  def current_game=(game)
    @current_game = game
  end

  def current_game
    @current_game ||= Game.find_by_name cookies[:current_game]
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="post">
  <div class="post-wrapper">
  <div class="mb-3" style="margin: auto; width: 350px;">
    <%= form.label :title, "#{ t '.title' }", style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div class="mb-3" style="margin: auto; width: 800px; height: fit-content; background-color: white">
    <%= form.label :body, "#{ t '.text' }", style: "display: block" %>
    <%= form.rich_text_area :body %>
  </div>

  </div>
  </div>

  <br>

  <div>
    <% if action_name == 'edit' %>
      <%= form.submit "#{ t '.edit' }", class: 'btn btn-success' %>
    <% else %>
      <%= form.submit "#{ t '.create' }", class: 'btn btn-success' %>
    <% end %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">
  <div class="_post">
    <div style="display: grid; padding-top: 10px; grid-template-columns: [avatar-start] 0 [author-start] 100px
                                                      [avatar-end] 0 [title-start] 250px [title-end] 100px [post-end];">
      <div style="grid-area: avatar">
        <% if User.find_by_id(post.user_id).avatar.attached? %>
          <%= image_tag User.find_by_id(post.user_id).avatar, size: "70", style: "border: 2px solid black" %>
        <% else %>
          <%= image_tag 'default_avatar.jpg', size: "70", style: "border: 2px solid black" %>
        <% end %>
      </div>
      <div style="grid-area: author">
        <p>
          <strong><%= t '.author' %>: </strong><%= User.find_by_id(post.user_id).nickname %>
        </p>
      </div>
      <div style="grid-area: title">
        <div class="title">
          <p>
            <h3><%= post.title %></h3>
          </p>
        </div>
      </div>
    </div>

    <hr>

    <div class="body">
      <p>
        <%= post.body %>
      </p>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= stylesheet_link_tag "posts_common", media: "all", "data-turbolinks-track": "reload" %>
<%= stylesheet_link_tag "posts_new_edit", media: "all", "data-turbolinks-track": "reload" %>

<main>
    <h1><%= t '.edit_t' %></h1>

    <% if @post.user_id == @current_user.id || @current_user.is_admin %>
        <%= render "form", post: @post %>
    <% else %>
        <div class="post">
          <div class="post-wrapper">
            <div class="alert-danger alert" style="margin: auto">
              <%= t '.warning' %>
            </div>
          </div>
        </div>
    <% end %>
  <br>

    <div>
      <%= link_to "#{ t '.show' }", @post, class: 'btn btn-info' %> |
      <%= link_to "#{ t '.posts' }", posts_path, class: 'btn btn-info' %>
    </div>
</main>

app/views/posts/index.html.erb
<%= stylesheet_link_tag "posts_common", media: "all", "data-turbolinks-track": "reload" %>
<%= stylesheet_link_tag "posts_index", media: "all", "data-turbolinks-track": "reload" %>

<main>
  <div style="width: fit-content; margin: auto;">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" role="alert" style="width: fit-content">
      <%= value %>
    </div>
    <br>
  <% end %>
  </div>

  <h1>
    <%= t '.ind' %>
    <%= current_game.name %>
  </h1>

  <div id="posts">
    <% @posts.each do |post| %>
      <div class="post">
        <div class="post-wrapper">
          <%= render post %>
        </div>
      </div>
      <div class="desc-section">
        <h5><%= link_to "#{ t '.show' }", post, class: 'btn btn-warning' %></h5>
        <h5><%= link_to "#{ t '.comments' }", comments_path + "?post=#{post.id}", class: 'btn btn-warning' %></h5>
      </div>
    <% end %>
  </div>

  <h5><%= link_to "#{ t '.new' }", new_post_path, class: 'btn btn-info' %></h5>
</main>

app/views/posts/new.html.erb
<%= stylesheet_link_tag "posts_common", media: "all", "data-turbolinks-track": "reload" %>
<%= stylesheet_link_tag "posts_new_edit", media: "all", "data-turbolinks-track": "reload" %>

<main>

  <h1><%= t '.title' %></h1>
      <%= render "form", post: @post %>
  <br>

  <div style="vertical-align: bottom;">
    <h5><%= link_to "#{ t '.posts' }", posts_path, class: 'btn btn-info' %></h5>
  </div>

</main>

app/views/posts/show.html.erb
<%= stylesheet_link_tag "posts_common", media: "all", "data-turbolinks-track": "reload" %>
<%= stylesheet_link_tag "posts_show", media: "all", "data-turbolinks-track": "reload" %>

<main>

  <div style="margin: auto; width: fit-content">
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>" role="alert" style="width: fit-content">
    <%= value %>
  </div>
  <br>
<% end %>
  </div>

  <div class="post" style="margin-top: 20px;">
    <div class="post-wrapper">
      <%= render @post %>
    </div>
  </div>

<div style="margin: auto; width: 500px">
  <h5>
    <% if @current_user.id == @post.user_id || @current_user.is_admin %>
      <%= link_to "#{ t '.edit' }", edit_post_path(@post), class: 'btn btn-warning' %> |
    <% end %>
    <%= link_to "#{ t '.posts' }", posts_path, class: 'btn btn-warning' %>
  </h5>

  <br>

  <% if @current_user.nickname == User.find_by_id(@post.user).nickname || @current_user.is_admin %>
    <%= button_to "#{ t '.delete' }", @post, method: :delete, class: 'btn btn-danger' %>
  <% end %>
</div>

</main>